### ISSUE TITLE
The Legend of Zelda Tears of the Kingdom Bugs

### ISSUE THREAD

**Issue by Kristijan1001** [yuzu-emu/yuzu#10226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 

### Description of Issue

* Transparency in Clouds

https://i.imgur.com/sEgT2wN.jpeg

https://i.imgur.com/lba3jDr.jpeg

* Pixelated Shadows on Objects that You use "Ultra Hand" On. Similar issue with Waterfall Effects & Some other Surfaces.

https://i.imgur.com/NFc7nb5.mp4

https://i.imgur.com/TcaEw5W.jpeg

https://i.imgur.com/aoa2nwn.jpeg

* Flickering Textures in Shrines. On the ground next to Link and on the Walls.

https://i.imgur.com/MxaUtnc.mp4

* Rain

https://i.imgur.com/JH7PovW.mp4 (Rain Working)

https://i.imgur.com/FGMKJAh.mp4 (Broken Rain)

* Flickering when aiming a Bow. (Fixed Using Shadow Resolution Patch "00D075AC 0B808052 00D075B0 17000014")

https://i.imgur.com/j4p2KWn.mp4

* Random Flickering of Graphics while playing, or when starting NPC Dialogue. (Fixed Using Shadow Resolution Patch "00D075AC 0B808052 00D075B0 17000014" )

https://i.imgur.com/2EaYbK6.mp4

* Some Clouds are Pixelated.

https://i.imgur.com/vKwT2w3.jpeg

* Depths are Semi-Working.

https://i.imgur.com/3wgZCmb.jpeg

Fix for Clouds + Depths

```
diff --git a/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp b/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
index fee510f..07c2b7b 100644
--- a/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
+++ b/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
@@ -339,9 +339,7 @@ Id EmitGetAttribute(EmitContext& ctx, IR::Attribute attr, Id vertex) {
         if (ctx.profile.support_vertex_instance_id) {
             return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.vertex_id));
         } else {
-            const Id index{ctx.OpLoad(ctx.U32[1], ctx.vertex_index)};
-            const Id base{ctx.OpLoad(ctx.U32[1], ctx.base_vertex)};
-            return ctx.OpBitcast(ctx.F32[1], ctx.OpISub(ctx.U32[1], index, base));
+            return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.vertex_index));
         }
     case IR::Attribute::BaseInstance:
         return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.base_instance));
@@ -386,9 +384,7 @@ Id EmitGetAttributeU32(EmitContext& ctx, IR::Attribute attr, Id) {
         if (ctx.profile.support_vertex_instance_id) {
             return ctx.OpLoad(ctx.U32[1], ctx.vertex_id);
         } else {
-            const Id index{ctx.OpLoad(ctx.U32[1], ctx.vertex_index)};
-            const Id base{ctx.OpLoad(ctx.U32[1], ctx.base_vertex)};
-            return ctx.OpISub(ctx.U32[1], index, base);
+            return ctx.OpLoad(ctx.U32[1], ctx.vertex_index);
         }
     case IR::Attribute::BaseInstance:
         return ctx.OpLoad(ctx.U32[1], ctx.base_instance);
diff --git a/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp b/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
index 639da1e..eeb4944 100644
--- a/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
+++ b/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
@@ -102,12 +102,7 @@ void Impl(TranslatorVisitor& v, u64 insn, bool is_bindless) {
         }
         IR::F32 value{v.ir.CompositeExtract(sample, element)};
         if (element < 2) {
-            IR::U32 casted_value;
-            if (element == 0) {
-                casted_value = v.ir.ConvertFToU(32, value);
-            } else {
-                casted_value = v.ir.ConvertFToS(16, value);
-            }
+            IR::U32 casted_value = v.ir.ConvertFToU(32, value);
             v.X(dest_reg, v.ir.ShiftLeftLogical(casted_value, v.ir.Imm32(8)));
         } else {
             v.F(dest_reg, value);
```

### Expected Behavior

See Above

### Reproduction Steps

See Above

### Log File

No Logs

### System Configuration

CPU: i9 9900k
GPU/Driver: 2070 Super
RAM: 32GBs
OS: Windows 11

**Comment by G-Spawn** [comment]
Feel free to reopen issue after the 12th.

**Comment by smiglo5** [comment]
Any save from "broken" depths will be welcome.

**Comment by Kristijan1001** [comment]
Don't really understand much but this is the fix for Clouds + Depths at least what i found:

```
diff --git a/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp b/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
index fee510f..07c2b7b 100644
--- a/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
+++ b/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
@@ -339,9 +339,7 @@ Id EmitGetAttribute(EmitContext& ctx, IR::Attribute attr, Id vertex) {
         if (ctx.profile.support_vertex_instance_id) {
             return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.vertex_id));
         } else {
-            const Id index{ctx.OpLoad(ctx.U32[1], ctx.vertex_index)};
-            const Id base{ctx.OpLoad(ctx.U32[1], ctx.base_vertex)};
-            return ctx.OpBitcast(ctx.F32[1], ctx.OpISub(ctx.U32[1], index, base));
+            return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.vertex_index));
         }
     case IR::Attribute::BaseInstance:
         return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.base_instance));
@@ -386,9 +384,7 @@ Id EmitGetAttributeU32(EmitContext& ctx, IR::Attribute attr, Id) {
         if (ctx.profile.support_vertex_instance_id) {
             return ctx.OpLoad(ctx.U32[1], ctx.vertex_id);
         } else {
-            const Id index{ctx.OpLoad(ctx.U32[1], ctx.vertex_index)};
-            const Id base{ctx.OpLoad(ctx.U32[1], ctx.base_vertex)};
-            return ctx.OpISub(ctx.U32[1], index, base);
+            return ctx.OpLoad(ctx.U32[1], ctx.vertex_index);
         }
     case IR::Attribute::BaseInstance:
         return ctx.OpLoad(ctx.U32[1], ctx.base_instance);
diff --git a/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp b/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
index 639da1e..eeb4944 100644
--- a/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
+++ b/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
@@ -102,12 +102,7 @@ void Impl(TranslatorVisitor& v, u64 insn, bool is_bindless) {
         }
         IR::F32 value{v.ir.CompositeExtract(sample, element)};
         if (element < 2) {
-            IR::U32 casted_value;
-            if (element == 0) {
-                casted_value = v.ir.ConvertFToU(32, value);
-            } else {
-                casted_value = v.ir.ConvertFToS(16, value);
-            }
+            IR::U32 casted_value = v.ir.ConvertFToU(32, value);
             v.X(dest_reg, v.ir.ShiftLeftLogical(casted_value, v.ir.Imm32(8)));
         } else {
             v.F(dest_reg, value);
```

**Comment by FernandoS27** [comment]
Ok it's now past the goalpost. So discussion is allowed.

**Comment by Kristijan1001** [comment]
> > Don't really understand much but this is the fix for Clouds + Depths at least what i found:
> > ```
> > diff --git a/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp b/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
> > index fee510f..07c2b7b 100644
> > --- a/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
> > +++ b/src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
> > @@ -339,9 +339,7 @@ Id EmitGetAttribute(EmitContext& ctx, IR::Attribute attr, Id vertex) {
> >          if (ctx.profile.support_vertex_instance_id) {
> >              return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.vertex_id));
> >          } else {
> > -            const Id index{ctx.OpLoad(ctx.U32[1], ctx.vertex_index)};
> > -            const Id base{ctx.OpLoad(ctx.U32[1], ctx.base_vertex)};
> > -            return ctx.OpBitcast(ctx.F32[1], ctx.OpISub(ctx.U32[1], index, base));
> > +            return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.vertex_index));
> >          }
> >      case IR::Attribute::BaseInstance:
> >          return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.base_instance));
> > @@ -386,9 +384,7 @@ Id EmitGetAttributeU32(EmitContext& ctx, IR::Attribute attr, Id) {
> >          if (ctx.profile.support_vertex_instance_id) {
> >              return ctx.OpLoad(ctx.U32[1], ctx.vertex_id);
> >          } else {
> > -            const Id index{ctx.OpLoad(ctx.U32[1], ctx.vertex_index)};
> > -            const Id base{ctx.OpLoad(ctx.U32[1], ctx.base_vertex)};
> > -            return ctx.OpISub(ctx.U32[1], index, base);
> > +            return ctx.OpLoad(ctx.U32[1], ctx.vertex_index);
> >          }
> >      case IR::Attribute::BaseInstance:
> >          return ctx.OpLoad(ctx.U32[1], ctx.base_instance);
> > diff --git a/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp b/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
> > index 639da1e..eeb4944 100644
> > --- a/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
> > +++ b/src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
> > @@ -102,12 +102,7 @@ void Impl(TranslatorVisitor& v, u64 insn, bool is_bindless) {
> >          }
> >          IR::F32 value{v.ir.CompositeExtract(sample, element)};
> >          if (element < 2) {
> > -            IR::U32 casted_value;
> > -            if (element == 0) {
> > -                casted_value = v.ir.ConvertFToU(32, value);
> > -            } else {
> > -                casted_value = v.ir.ConvertFToS(16, value);
> > -            }
> > +            IR::U32 casted_value = v.ir.ConvertFToU(32, value);
> >              v.X(dest_reg, v.ir.ShiftLeftLogical(casted_value, v.ir.Imm32(8)));
> >          } else {
> >              v.F(dest_reg, value);
> > ```
> 
> Hmm the first part is weird.
> 
> It changes gl_VertexId == gl_VertexIndex - gl_VertexBaseARB to just gl_VertexId == gl_VertexIndex.
> 
> That sounds wrong?
> 
> The second thing, could be. I need to do hardware tests for that instruction.
> 
> Where did you get this fixed? Who wrote them?

Some people on reddit. It fixes Depths and the Pixel Clouds.

**Comment by FernandoS27** [comment]
I looked into the Vulkan specification and it turns out this "gl_VertexId == gl_VertexIndex - gl_VertexBaseARB to just gl_VertexId == gl_VertexIndex." is correct.

https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt

```
7. What names do we really want to use for
        gl_VertexIndex             base, base+1, base+2, ...
        gl_InstanceIndex           base, base+1, base+2, ...

     RESOLUTION: Use the names above.

     Note that gl_VertexIndex is equivalent to OpenGL's gl_VertexID in that
     it includes the value of the baseVertex parameter. gl_InstanceIndex is
     NOT equivalent to OpenGL's gl_InstanceID because gl_InstanceID does NOT
     include the baseInstance parameter.
```
     
    It's just confusing because it's not the same case as gl_instanceIndex

**Comment by Kristijan1001** [comment]
Some Patches made by: ChucksFeedAndSeed, LonelySolon, igoticecream, Shadows really important since it fixes a really bad bug of the whole Graphics flickering when aiming or talking to NPCs.

```
// 30 FPS Patch v3
@enabled
0090E9C4 41008052
00EBD158 41008052
0090E990 55008052
0090EA38 55008052
0090EAA8 48008052
0090EA40 4C008052
0090E98C EB031F2A
019BF104 1F2003D5
019CA668 1F2003D5
@stop

// 60 FPS Patch v3
@enabled
0090E9C4 21008052
00EBD158 21008052
0090E990 35008052
0090EA38 35008052
0090EAA8 28008052
0090EA40 2C008052
0090E98C EB031F2A
019BF104 1F2003D5
019CA668 1F2003D5
@stop

// Dynamic Resolution (Something something configs, might not do anything)
@enabled
027CA074 000080D2
00d07600 1F2003D5
00d07928 1F2003D5
@stop

// FSR (Pretty much just skipping the entire shader? (I could be wrong))
@enabled
027CA0DC 000080D2
0188D0D4 000080D2
00AEAC44 1F2003D5
@stop 

// Shadows Resolution
@enabled
00D075AC 0B808052
00D075B0 17000014
@stop

// Options for shadow resolution (may effect cascade distance)
// | Code              | Resolution |
// |:-----------------:|:----------:|
// | 00D075AC 0B018052 | 8          |
// | 00D075AC 0B028052 | 16         |
// | 00D075AC 0B048052 | 32         |
// | 00D075AC 0B088052 | 64         |
// | 00D075AC 0B108052 | 128        |
// | 00D075AC 0B208052 | 256        |
// | 00D075AC 0B408052 | 512        |
// | 00D075AC 0B808052 | 1024       |
// | 00D075AC 0B008152 | 2048       | (Crashes under certain conditions! Use 1024 if you encounter this)

// FXAA (Probably does nothing, but makes sure FXAA is not enabled)
@enabled
027CA13C 000080D2
0188D0A0 000080D2
@stop

// LOD (May only have an effect with certain settings on emulator, or specifically only on hardware)
@enabled
00030BFC 0030B8D2
00837FBC 0030B8D2
021DEC24 0030B8D2
@stop

// Disable FSR Downscaling
@enabled
00CAD340 08008052
@stop

// Disable quality reduction when framerate dips
// (game changes model LODs etc to match handheld, causing textures etc to visibly change)
@enabled
00CAD34C C0000014
@stop

// Force 1792x1008 Internal Resolution instead of 1600x900
@enabled
00CEA5BC F50300AA
00CEA5C0 83F6FE97
00CEA5C4 140040B9
00CEA5C8 E00315AA
00CEA5D4 F50700F9
00CEA5D8 08E080D2
00CEA5DC 097E80D2
00CEA5E0 0001221E
00CEA5E4 0001221E
00CEA5EC 2101221E
@stop

// Force Full-Res Rendering 1080p instead of 1600x900, Disables Postprocessing stuff & Ambient Occlusion
// @enabled
// 00CEA77C 15000014
// @stop

// Unlimited Amiibo Usage
@enabled
0195BADC 14000014
@stop
```

**Comment by BSoDGamingYT** [comment]
> Some Patches made by: ChucksFeedAndSeed, LonelySolon, igoticecream, Shadows really important since it fixes a really bad bug of the whole Graphics flickering when aiming or talking to NPCs.
> 
> ```
> // 30 FPS Patch v3
> @enabled
> 0090E9C4 41008052
> 00EBD158 41008052
> 0090E990 55008052
> 0090EA38 55008052
> 0090EAA8 48008052
> 0090EA40 4C008052
> 0090E98C EB031F2A
> 019BF104 1F2003D5
> 019CA668 1F2003D5
> @stop
> 
> // 60 FPS Patch v3
> @enabled
> 0090E9C4 21008052
> 00EBD158 21008052
> 0090E990 35008052
> 0090EA38 35008052
> 0090EAA8 28008052
> 0090EA40 2C008052
> 0090E98C EB031F2A
> 019BF104 1F2003D5
> 019CA668 1F2003D5
> @stop
> 
> // Dynamic Resolution (Something something configs, might not do anything)
> @enabled
> 027CA074 000080D2
> 00d07600 1F2003D5
> 00d07928 1F2003D5
> @stop
> 
> // FSR (Pretty much just skipping the entire shader? (I could be wrong))
> @enabled
> 027CA0DC 000080D2
> 0188D0D4 000080D2
> 00AEAC44 1F2003D5
> @stop 
> 
> // Shadows Resolution
> @enabled
> 00D075AC 0B808052
> 00D075B0 17000014
> @stop
> 
> // Options for shadow resolution (may effect cascade distance)
> // | Code              | Resolution |
> // |:-----------------:|:----------:|
> // | 00D075AC 0B018052 | 8          |
> // | 00D075AC 0B028052 | 16         |
> // | 00D075AC 0B048052 | 32         |
> // | 00D075AC 0B088052 | 64         |
> // | 00D075AC 0B108052 | 128        |
> // | 00D075AC 0B208052 | 256        |
> // | 00D075AC 0B408052 | 512        |
> // | 00D075AC 0B808052 | 1024       |
> // | 00D075AC 0B008152 | 2048       | (Crashes under certain conditions! Use 1024 if you encounter this)
> 
> // FXAA (Probably does nothing, but makes sure FXAA is not enabled)
> @enabled
> 027CA13C 000080D2
> 0188D0A0 000080D2
> @stop
> 
> // LOD (May only have an effect with certain settings on emulator, or specifically only on hardware)
> @enabled
> 00030BFC 0030B8D2
> 00837FBC 0030B8D2
> 021DEC24 0030B8D2
> @stop
> 
> // Disable FSR Downscaling
> @enabled
> 00CAD340 08008052
> @stop
> 
> // Disable quality reduction when framerate dips
> // (game changes model LODs etc to match handheld, causing textures etc to visibly change)
> @enabled
> 00CAD34C C0000014
> @stop
> 
> // Force 1792x1008 Internal Resolution instead of 1600x900
> @enabled
> 00CEA5BC F50300AA
> 00CEA5C0 83F6FE97
> 00CEA5C4 140040B9
> 00CEA5C8 E00315AA
> 00CEA5D4 F50700F9
> 00CEA5D8 08E080D2
> 00CEA5DC 097E80D2
> 00CEA5E0 0001221E
> 00CEA5E4 0001221E
> 00CEA5EC 2101221E
> @stop
> 
> // Force Full-Res Rendering 1080p instead of 1600x900, Disables Postprocessing stuff & Ambient Occlusion
> // @enabled
> // 00CEA77C 15000014
> // @stop
> 
> // Unlimited Amiibo Usage
> @enabled
> 0195BADC 14000014
> @stop
> ```

Mods for fixing rendering issues aren't useful here, devs will need to actually fix them...not patch them with mods. Feel free to post them elsewhere (Like on the discord), but they are only crowding an otherwise useful thread

**Comment by FernandoS27** [comment]
> > 
> 
> 1 developer is getting his ticket soon, will dump the game and will look into the booting issues.
> 
> I'll get on it later tonight.
Update:

Maide now has the game and byte got it as well. I asked Maide to PR the fixes you posted as we verified they should work (we need to check the game).

**Comment by Sincasios** [comment]
And the save timestamp, that points to 1970,

**Comment by Squall-Leonhart** [comment]
> And the save timestamp, that points to 1970,

This requires implementing the Time service updates from the 15.0.x and later firmwares, refer to https://github.com/Ryujinx/Ryujinx/pull/4822 (or not)

**Comment by radonthetyrant** [comment]
@Squall-Leonhart 

> What i noticed wasn't mentioned was the exception that prevents TOTK from starting without a ipswitch patch.

Which IPSwitch patch is that that is needed? I am stuck at this exact error message that you posted

**Comment by Squall-Leonhart** [comment]
#10237 will fix it

**Comment by liamwhite** [comment]
I need to implement the cache storage stuff correctly but am looking at time services for the moment

**Comment by Squall-Leonhart** [comment]
> I need to implement the cache storage stuff correctly but am looking at time services for the moment

Added some idea's to the PR.

**Comment by Senjosei** [comment]
i've been using a different fix for depths which seemed more correct.
in `vk_pipeline_cache.cpp line 300`  change `.support_vertex_instance_id = false,` to `.support_vertex_instance_id = true,`. Dunno why that wasnt true before but it fixed dephts

**Comment by liamwhite** [comment]
The posted fix seems correct - gl_VertexID isn't supported in Vulkan GLSL, you're supposed to use gl_VertexIndex.

**Comment by Squall-Leonhart** [comment]
> Dunno why that wasnt true before but it fixed dephts

you're forcing vertex instances to be cached, which is not a good idea.

**Comment by Sincasios** [comment]
I see that the "ultra-hand" shadow is already reported. I took another screenshot:
![ultrahand](https://github.com/yuzu-emu/yuzu/assets/50843918/a1c34a0e-83c4-4a27-982d-9aea9e7d910d)

**Comment by Silvl89** [comment]
Rain
https://i.imgur.com/JH7PovW.mp4 (Rain Working)

https://i.imgur.com/FGMKJAh.mp4 (Broken Rain) ?????????

**Comment by Kristijan1001** [comment]
> Rain https://i.imgur.com/JH7PovW.mp4 (Rain Working)
> 
> https://i.imgur.com/FGMKJAh.mp4 (Broken Rain) ?????????

At a certain angles rain is like in the matrix its slow falling

**Comment by Silvl89** [comment]
> > Chuva https://i.imgur.com/JH7PovW.mp4 (Rain Working)
> > https://i.imgur.com/FGMKJAh.mp4 (Chuva Quebrada) ?????????
> 
> Em certos ângulos, a chuva é como na matriz, sua queda lenta

Yes, Any solution ???

**Comment by Kristijan1001** [comment]
> > > Chuva https://i.imgur.com/JH7PovW.mp4 (Rain Working)
> > > https://i.imgur.com/FGMKJAh.mp4 (Chuva Quebrada) ?????????
> > 
> > 
> > Em certos ângulos, a chuva é como na matriz, sua queda lenta
> 
> Yes, Any solution ???

No? Afik has not been fixed. Wait for updates..

**Comment by Silvl89** [comment]
> > > > Chuva https://i.imgur.com/JH7PovW.mp4 (Rain Working)
> > > > https://i.imgur.com/FGMKJAh.mp4 (Chuva Quebrada) ?????????
> > > 
> > > 
> > > Em certos ângulos, a chuva é como na matriz, sua queda lenta
> > 
> > 
> > Yes, Any solution ???
> 
> No? Afik has not been fixed. Wait for updates..

I will wait then

**Comment by edergames29** [comment]
there is a bug that after the introduction after the first shrine you have to make the tree trunk bridge the save game has infinite loading

**Comment by DonelBueno** [comment]
I don't have these:

- Pixelated Shadows on Objects that You use "Ultra Hand" On
- Flickering Textures in Shrines. On the ground next to Link and on the Walls.

But "transparency on clouds" and "rain" also happen here.

Windows 10, GTX 1070, Ryzen 5800x, EA 3588.

**Comment by Sincasios** [comment]
Another issue: When I take a photo, at least for the "hylian archive" (a photo to some identificable object) it "blocks" for 0,5 seconds or something like that, it's not fluid. The major problem is that sometimes it shows the photo, click to "add" or "replace" and the game blocks and I need to close Yuzu.

**Comment by BParks21** [comment]
This can sometimes happen without the shadow fix mod if I aim my weapon or bow. No mods installed producing this. Shadow fix mod prevents it. I see at the top of this issue the flickering when aiming is crossed off. I don't know if it's crossed off because it's fixed with or without the shadow mod.. All I know is things still break without it. For me at least on Pascal. Also on pascal I don't have the Ultra Hand shadow flickering or Shrine flickering at all. 
![Screenshot (114)](https://github.com/yuzu-emu/yuzu/assets/12180630/792e4b03-8d45-45d4-a435-96bc6a9aeb1d)

**Comment by ChrisWNY** [comment]
The CHASM is completely messed up in Yuzu. I've been using Vulkan, 2x scaling, 1.1.0 patch, 60fps mod, etc. The underground chasm area doesn't render properly and there's no way to get out, rendering the game unplayable in that area.

**Comment by FernandoS27** [comment]
> The CHASM is completely messed up in Yuzu. I've been using Vulkan, 2x scaling, 1.1.0 patch, 60fps mod, etc. The underground chasm area doesn't render properly and there's no way to get out, rendering the game unplayable in that area.
 Are you using latest EA/Mainline we fixed the depths on release unless the PR got untagged.

**Comment by ChrisWNY** [comment]
I just downloaded v1433...I'll re-test and report back shortly. That would be awesome if it's fixed...

**Comment by arananegra** [comment]
Has anyone noticed a bug where the swords change action shows the previews incomplete? For example, a sword + a rock shows only the rock

**Comment by anna-s-h** [comment]
> there is a bug that after the introduction after the first shrine you have to make the tree trunk bridge the save game has infinite loading

Is this another case of #10303? Have you fixed it?

**Comment by MorningStarrrrrrrrr** [comment]
~* Flickering when aiming a Bow. (Fixed Using Shadow Resolution Patch "00D075AC 0B808052 00D075B0 17000014")~ FIXED

Please tell me why im dumbo, Im trying to fix that problem adding lines, "making" this patches etc but I still have problem with flickering lights/black flicking when aiming or some random light i quess flickering

Righ now i just have this 1.1.0 patch and i have lines

// Shadows Resolution
@enabled
00D075AC 0B808052
00D075B0 17000014
@stop

// Options for shadow resolution (may effect cascade distance)
// | Code              | Resolution |
// |:-----------------:|:----------:|
// | 00D075AC 0B018052 | 8          |
// | 00D075AC 0B028052 | 16         |
// | 00D075AC 0B048052 | 32         |
// | 00D075AC 0B088052 | 64         |
// | 00D075AC 0B108052 | 128        |
// | 00D075AC 0B208052 | 256        |
// | 00D075AC 0B408052 | 512        |
// | 00D075AC 0B808052 | 1024       |
// | 00D075AC 0B008152 | 2048       | (Crashes under certain conditions! Use 1024 if you encounter this)


BUT it's worthless or Im doing something wrong, please help me

**Comment by Kristijan1001** [comment]
> ~* Flickering when aiming a Bow. (Fixed Using Shadow Resolution Patch "00D075AC 0B808052 00D075B0 17000014")~ FIXED
> 
> Please tell me why im dumbo, Im trying to fix that problem adding lines, "making" this patches etc but I still have problem with flickering lights/black flicking when aiming or some random light i quess flickering
> 
> Righ now i just have this 1.1.0 patch and i have lines
> 
> // Shadows Resolution @enabled 00D075AC 0B808052 00D075B0 17000014 @Stop
> 
> // Options for shadow resolution (may effect cascade distance) // | Code | Resolution | // |:-----------------:|:----------:| // | 00D075AC 0B018052 | 8 | // | 00D075AC 0B028052 | 16 | // | 00D075AC 0B048052 | 32 | // | 00D075AC 0B088052 | 64 | // | 00D075AC 0B108052 | 128 | // | 00D075AC 0B208052 | 256 | // | 00D075AC 0B408052 | 512 | // | 00D075AC 0B808052 | 1024 | // | 00D075AC 0B008152 | 2048 | (Crashes under certain conditions! Use 1024 if you encounter this)
> 
> BUT it's worthless or Im doing something wrong, please help me

Update ur game.

**Comment by MorningStarrrrrrrrr** [comment]
> Update ur game.

I was thinking i done it? or i did something wrong? I don't have crashes anymore, clouds are fine, only this problem occuring

**Comment by BSoDGamingYT** [comment]
> > Update ur game.
> 
> I was thinking i done it? or i did something wrong? I don't have crashes anymore, clouds are fine, only this problem occuring

This is not a support forum...please do not comment here asking for help with mods. Use the discord for this

**Comment by Voron3DD** [comment]
This is probably already a known issue, but there are holes in the landscape geometry in the Depths. Also, the problem with stuttering rain extends to some floating particles. They periodically freeze in the air.
![0100f2c0115b6000_2023-05-16_22-49-16-904](https://github.com/yuzu-emu/yuzu/assets/18101263/3d87028a-c2e4-460b-9e20-f0d2cb406114)

**Comment by Squall-Leonhart** [comment]
it's probably video memory related too, given the delayed occurence

**Comment by Squall-Leonhart** [comment]
I think i'm wrong about the vram being a factor with the particles issue, this could be the same issue that affects the ultra hand being partially broken, and might be fixed by something @liamwhite  is working on right now.

**Comment by EgoBizarro** [comment]
> ~I think i'm wrong about the vram being a factor with the particles issue, this could be the same issue that affects the ultra hand being partially broken, and might be fixed by something @liamwhite is working on right now.~
> 
> wait, particle issue is opengl only, its likely something else.

If you mean the barrier attachment feedback loops change, it hasn't fixed the particle issue. And I'm getting it with Vulkan btw.

**Comment by Sincasios** [comment]
I tested 3062.

I didn't had problems with crashing (I have 3060 with 12 GB and play 1x) but had some graphical glitchers.

The ultrahand shadow now is OK, and the first time that I changed to some weapon it stalled a lot of time (and the game show a "Loading" message in top of the weapon list that I never saw until now), if I go again to the same weapon it goes fine (I didnt see message of shadder compilation). I closed Yuzu and opened again and now change betwen weapons is fine.

What I see is a flikering effect in the some objects, very noticeable in the boards, for example in Hatellia: https://youtu.be/Lx-kCziPHjU
When you go close to a board it flickers. There are some other issues,

**Comment by Toverrijst** [comment]
Flickering textures issue in shrines seems to disappear when you switch from normal to high graphics accuracy.

**Comment by ChrisWNY** [comment]
> Flickering textures issue in shrines seems to disappear when you switch from normal to high graphics accuracy.

Agree...there are some trade-offs if you use normal or low graphics accuracy, sometimes a glitch here and there.

**Comment by Sincasios** [comment]
> I tested 3602.
> 
> I didn't had problems with crashing (I have 3060 with 12 GB and play 1x) but had some graphical glitchers.
> 
> The ultrahand shadow now is OK, and the first time that I changed to some weapon it stalled a lot of time (and the game show a "Loading" message in top of the weapon list that I never saw until now), if I change again to the same weapon it goes fine (I didnt see message of shadder compilation). I closed Yuzu and opened again and now change betwen weapons is fine.
> 
> What I see is a flikering effect in some objects, very noticeable in the boards, for example in Hatelia: https://youtu.be/Lx-kCziPHjU When you go close to a board it flickers.
Still flickering with 3609

**Comment by KarenNscmnto** [comment]
EA 3612
CPU: Ryzen 5 5600G
GPU: RX580 8GB (Driver 23.3.1)
RAM: 16GB
API: Vulkan and OpenGL
Some 3d models, apparently all circular or cylindrical, have a kind of wireframe marking their polygons, it happens regardless of MODs and only in 1x resolution both in Vulkan and OpenGL.

![Lines](https://github.com/yuzu-emu/yuzu/assets/64856031/2407ea6b-0f48-4369-9f7c-29539977f6e5)

At the moment with this configuration using VULKAN, the only graphical bugs I've seen are:
That wireframe bug.
Slowmotion rain.
Sometimes the weather effects go crazy during the teleport animation.
I use very few mods, basically, resolution, fsr removal and anisotropic filter correction.

**Comment by KarenNscmnto** [comment]
> > EA 3612 CPU: Ryzen 5 5600G GPU: RX580 8GB (Driver 23.3.1) RAM: 16GB API: Vulkan and OpenGL Some 3d models, apparently all circular or cylindrical, have a kind of wireframe marking their polygons, it happens regardless of MODs and only in 1x resolution both in Vulkan and OpenGL.
> > ![Lines](https://user-images.githubusercontent.com/64856031/241061555-2407ea6b-0f48-4369-9f7c-29539977f6e5.png)
> > At the moment with this configuration using VULKAN, the only graphical bugs I've seen are: That wireframe bug. Slowmotion rain. Sometimes the weather effects go crazy during the teleport animation. I use very few mods, basically, resolution, fsr removal and anisotropic filter correction.
> 
> All known bugs, and the lines are caused by AMD drivers, you can fix it by using Shadow Resolution Patch according to some modders.
> 
> You should also be using 23.4.1 with that GPU.

The Shadow Resolution Patch fix another problem i didn't have, isn't this glitch, about the driver version, this version was recomended to be using by one of yuzu mods on discord. This problem happens with (not necessary any more)shadow mod too and only on x1 scale.

**Comment by Squall-Leonhart** [comment]
The thick lines are caused by forcing AF afaik.

**Comment by KarenNscmnto** [comment]
> The thick lines are caused by forcing AF afaik.

Sadly the problem persists with any AF config, with and without the AF MOD Fix. :(

**Comment by ChrisWNY** [comment]
Build 1445...odd issue where audio drops out not long after TOTK loads up. Audio is working in the initial start-up menu, but cuts out after the game loads...

**Comment by StatusCode404** [comment]
> > > EA 3612 CPU: Ryzen 5 5600G GPU: RX580 8GB (Driver 23.3.1) RAM: 16GB API: Vulkan and OpenGL Some 3d models, apparently all circular or cylindrical, have a kind of wireframe marking their polygons, it happens regardless of MODs and only in 1x resolution both in Vulkan and OpenGL.
> > > ![Lines](https://user-images.githubusercontent.com/64856031/241061555-2407ea6b-0f48-4369-9f7c-29539977f6e5.png)
> > > At the moment with this configuration using VULKAN, the only graphical bugs I've seen are: That wireframe bug. Slowmotion rain. Sometimes the weather effects go crazy during the teleport animation. I use very few mods, basically, resolution, fsr removal and anisotropic filter correction.
> > 
> > 
> > All known bugs, and the lines are caused by AMD drivers, you can fix it by using Shadow Resolution Patch according to some modders.
> > You should also be using 23.4.1 with that GPU.
> 
> The Shadow Resolution Patch fix another problem i didn't have, isn't this glitch, about the driver version, this version was recomended to be using by one of yuzu mods on discord. This problem happens with (not necessary any more)shadow mod too and only on x1 scale.
> 
> EDIT1: I will try the low res versions of shadow mod. EDIT2: The problem persists. :( FINAL_EDIT: The problem persists on latest driver.

Has anyone checked on Linux and with latest mesa and RADV?

Perhaps it is only a Windows thing?

**Comment by KarenNscmnto** [comment]
> > > > EA 3612 CPU: Ryzen 5 5600G GPU: RX580 8GB (Driver 23.3.1) RAM: 16GB API: Vulkan and OpenGL Some 3d models, apparently all circular or cylindrical, have a kind of wireframe marking their polygons, it happens regardless of MODs and only in 1x resolution both in Vulkan and OpenGL.
> > > > ![Lines](https://user-images.githubusercontent.com/64856031/241061555-2407ea6b-0f48-4369-9f7c-29539977f6e5.png)
> > > > At the moment with this configuration using VULKAN, the only graphical bugs I've seen are: That wireframe bug. Slowmotion rain. Sometimes the weather effects go crazy during the teleport animation. I use very few mods, basically, resolution, fsr removal and anisotropic filter correction.
> > > 
> > > 
> > > All known bugs, and the lines are caused by AMD drivers, you can fix it by using Shadow Resolution Patch according to some modders.
> > > You should also be using 23.4.1 with that GPU.
> > 
> > 
> > The Shadow Resolution Patch fix another problem i didn't have, isn't this glitch, about the driver version, this version was recomended to be using by one of yuzu mods on discord. This problem happens with (not necessary any more)shadow mod too and only on x1 scale.
> > EDIT1: I will try the low res versions of shadow mod. EDIT2: The problem persists. :( FINAL_EDIT: The problem persists on latest driver.
> 
> Has anyone checked on Linux and with latest mesa and RADV?
> 
> Perhaps it is only a Windows thing?

Apparently most recent AMD GPUs are not suffering this glitch, probably a Polaris related glitch, do not know about linux mesa.

**Comment by Plast15** [comment]
> > > > > EA 3612 CPU: Ryzen 5 5600G GPU: RX580 8GB (Driver 23.3.1) RAM: 16GB API: Vulkan and OpenGL Some 3d models, apparently all circular or cylindrical, have a kind of wireframe marking their polygons, it happens regardless of MODs and only in 1x resolution both in Vulkan and OpenGL.
> > > > > ![Lines](https://user-images.githubusercontent.com/64856031/241061555-2407ea6b-0f48-4369-9f7c-29539977f6e5.png)
> > > > > At the moment with this configuration using VULKAN, the only graphical bugs I've seen are: That wireframe bug. Slowmotion rain. Sometimes the weather effects go crazy during the teleport animation. I use very few mods, basically, resolution, fsr removal and anisotropic filter correction.
> > > > 
> > > > 
> > > > All known bugs, and the lines are caused by AMD drivers, you can fix it by using Shadow Resolution Patch according to some modders.
> > > > You should also be using 23.4.1 with that GPU.
> > > 
> > > 
> > > The Shadow Resolution Patch fix another problem i didn't have, isn't this glitch, about the driver version, this version was recomended to be using by one of yuzu mods on discord. This problem happens with (not necessary any more)shadow mod too and only on x1 scale.
> > > EDIT1: I will try the low res versions of shadow mod. EDIT2: The problem persists. :( FINAL_EDIT: The problem persists on latest driver.
> > 
> > 
> > Has anyone checked on Linux and with latest mesa and RADV?
> > Perhaps it is only a Windows thing?
> 
> Apparently most recent AMD GPUs are not suffering this glitch, probably a Polaris related glitch, do not know about linux mesa.

I'm having the same issue my specs are pretty much the same except for my cpu witch is a Ryzen 5 2600 (I'm on the latest amd driver as of now 23.5.2 and on yuzuEA 3702) i used OpenGL SPIR-V and it got rid of the issue but my game couldn't run as well as when it is running on vulkan I was searching about this bug and found a similar issue on a pokemon game where the wireframes would show up too and someone made a mod that actually fixed it I wonder if the same could happen in this scenario

**Comment by BParks21** [comment]
Particles and rain seem fixed.

**Comment by BParks21** [comment]
Ultra hand shadows seemed fixed as well. At least in my testing using a 20 series Nvidia GPU.

**Comment by KarenNscmnto** [comment]
From my original comment the only mentioned issue that is present yet is the wireframe render issue on towers panel and some other meshes(from the screenshot) in Windows OpenGL/Vulkan.

EA Build: 3735
RX 580 8gb | 23.3.1

**Comment by BParks21** [comment]
There are still flickering textures on the ground in shrines. Very minor.

**Comment by Squall-Leonhart** [comment]
The flickering ground textures occur on Switch hardware as well

**Comment by BParks21** [comment]
> The flickering ground textures occur on Switch hardware as well

The part of the ground right when link enters a shrine? Like in the example above in the first post?

**Comment by brentleyjones** [comment]
Doesn't do that on hardware. This isn't referring to the AO flicker.

**Comment by Squall-Leonhart** [comment]
> Doesn't do that on hardware. This isn't referring to the AO flicker.

it does.

**Comment by brentleyjones** [comment]
It doesn't do the flicker on the ground as you enter the shrine. I've compared. This is still an emulation only bug.

**Comment by liamwhite** [comment]
Ground flicker is fixed by #10560 (but that PR is unworkable for many reasons)
