### ISSUE TITLE
Heavy video glitching and inability to get past the main menu in Alien Isolation 

### ISSUE THREAD

**Issue by nesper8** [yuzu-emu/yuzu#11057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1490

### Description of Issue

The issues are as follows

- The intro videos past the 20th Century Fox one are heavily glitched
![Screenshot from 2023-07-09 14-22-49](https://github.com/yuzu-emu/yuzu/assets/57890520/aa93ca5c-2715-40e4-a615-e1d24cbe41f3)

- The Main Menu background is not being rendered properly (the red blinking from the Sevastopol is being rendered properly but I don't have the subhuman reflex to screenshot it)
![Screenshot from 2023-07-09 14-15-42](https://github.com/yuzu-emu/yuzu/assets/57890520/57529dac-34c1-4109-93aa-a14e644c7d73)

- And finally the game crashes when trying to start a new game
![Screenshot from 2023-07-09 14-12-48](https://github.com/yuzu-emu/yuzu/assets/57890520/45ad56fa-4d35-4331-892f-e3b3d532d80f)

Thank you

### Expected Behavior

- The feral interactive, creative assembly and sega intro videos should play without any problems
- Main menu should render properly 
- Emulator should start the game properly without any problems

### Reproduction Steps

Install Alien Isolation with the 1.1.4_60709 update
Launch the Game try to start a New Game

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11994822/yuzu_log.txt.old.txt)

### System Configuration

CPU: i5-6200U
GPU/Driver: AMD R5 M330 (Mesa 23.1.3)
RAM: 16 GB
OS: Arch Linux

**Comment by goldenx86** [comment]
Can confirm it affects any hardware combination.
It's some issue with video decoding, affects both GPU and CPU decoding. Once in-game, rendering is good.

**Comment by nesper8** [comment]
@goldenx86 I'm unable to get in-game at all
What is the settings you have used?

**Comment by nesper8** [comment]
bumping issue for visibility
thank you for understanding

**Comment by nesper8** [comment]
bumping again due to issue not being fixed in latest mainline version as of today

**Comment by benderscruffy** [comment]
using Mainline 1581
Alien Isolation with the 1.1.4_60709 update goes ingame in windows
still has the problem of the video glitching
maybe it doesnt go ingame cause of Linux

**Comment by Squall-Leonhart** [comment]
may be fixed by https://github.com/yuzu-emu/yuzu/pull/12461

**Comment by Kelebek1** [comment]
> may be fixed by #12461

Not fixed. We're not generating the VP9 bitstream correctly for ffmpeg. I didn't touch that code in my rework, and I've looked at this issue multiple times now and I don't know what the problem is.
