### ISSUE TITLE
[Android] Super Mario Odyssey - New Crashes introduced in new Yuzu Playstore Early Access build

### ISSUE THREAD

**Issue by NocturnalBlue** [yuzu-emu/yuzu#12049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 2f9487cd3

### Description of Issue

The new Android Playstore Early Access build exhibits new game crashes that didn't exist before.
●Super Mario Odyssey crashes/locks up, mainly during level select. The game freezes, but the music continues playing. During this state, exiting the game doesn't work. You have to exit the app manually.

### Expected Behavior

No Crashes or Freezes.

### Reproduction Steps

●Super Mario Odyssey - scroll around in the level select menu, might take a few attempts to reproduce.

### Log File

[SMOyuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13369285/SMOyuzu_log.txt)

### System Configuration

CPU: Snaodragon 8 Gen 2
GPU/Driver: Adreno 740/Turnip R8
RAM: 12GB
OS: Android 14

**Comment by djdp77** [comment]
@M-hyun could you try using the Android Artifact from here: https://github.com/yuzu-emu/yuzu/pull/12036

You can get it here as well: https://nightly.link/yuzu-emu/yuzu/actions/runs/6871677828

**Comment by brujo5** [comment]
> @M-hyun could you try using the Android Artifact from here: #12036
> 
> You can get it here as well: https://nightly.link/yuzu-emu/yuzu/actions/runs/6871677828

I have experienced these crashes in some games since the new EA version, but some are specifically FFMPEG and VP9 audio decoder

[yuzu_log_audio crash.txt](https://github.com/yuzu-emu/yuzu/files/13370339/yuzu_log_audio.crash.txt)

**Comment by brujo5** [comment]
My crash is audio decoder bug since the crashes are solved if I disable the audio engine (null)

**Comment by NocturnalBlue** [comment]
> @M-hyun could you try using the Android Artifact from here: #12036
> 
> You can get it here as well: https://nightly.link/yuzu-emu/yuzu/actions/runs/6871677828

I tried this, it seems to fix that freeze but now the game crashes randomly, similarly to what I mention in my P5R issue.
[SMO-t1-log.txt](https://github.com/yuzu-emu/yuzu/files/13370496/SMO-t1-log.txt)

**Comment by liamwhite** [comment]
The audio decoder bug is caused by https://github.com/mozilla/cubeb/pull/768

**Comment by NocturnalBlue** [comment]
The original reported crash seems to be fixed.

**Comment by NocturnalBlue** [comment]
Me and Haradox have confirmed that the game does indeed still crash, so I'm reopening this.
Here is the new crash log -
[SMO log 137.txt](https://github.com/yuzu-emu/yuzu/files/13434305/SMO.log.137.txt)

**Comment by brujo5** [comment]
so still query cache thing. 

This problem is not exclusive to this game, it happens with others too. I have mentioned it in my other posts, for example in crysis 1 remastered, assassin's creed 2, etc. The emulation freezes and the fps drops to 0.

One way to mitigate this problem in Mario Odyssey is to use the turnip devel-2 driver that was shared some time ago by the skyline dev mark after the kgsl (with their own fixes) . This is how I solved this problem in my case. but I don't know if the driver is compatible with a725,730,740.

I think there is also some regression in the mesa source also

**Comment by brujo5** [comment]
the same thing happens here, FPS drop to 0.

https://github.com/yuzu-emu/yuzu/issues/12126
