### ISSUE TITLE
Proper viewport flip emulation

### ISSUE THREAD

**Issue by Eloeri** [yuzu-emu/yuzu#2703]
Games like Celeste and Axiom verge have the issue where the screen is rendered upside down, changes when APIs are swapped.

[](url)
<meta name="titleids"  content="01002B30028F6000,0100052004384000">

![celeste1](https://user-images.githubusercontent.com/42394653/60931265-93289480-a27e-11e9-8b64-b8ebaa914e06.jpg)

![celeste2](https://user-images.githubusercontent.com/42394653/60931264-93289480-a27e-11e9-9ed2-b44e4c7c671b.jpg)

![celeste3](https://user-images.githubusercontent.com/42394653/60931263-93289480-a27e-11e9-8b23-ea556d22611d.jpg)

![celeste4](https://user-images.githubusercontent.com/42394653/60931266-93289480-a27e-11e9-931e-f3113bc34c1b.jpg)

**Comment by ReinUsesLisp** [comment]
The issue I had with Vulkan was related to Android's vertical flip not being emulated.

On OpenGL our current approach harms transform feedbacks writing to `gl_Position.y` due to in-vertex shader flipping. To fix this we have to use GL_ARB_clip_control.

**Comment by alivefromupstairs** [comment]
any solution?

**Comment by ReinUsesLisp** [comment]
gdkchan from Ryujinx found there's a register in viewport configuration that controls an extra flipping flag. It is exposed in Nvidia's OpenGL driver through [NV_viewport_swizzle](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_viewport_swizzle.txt). Emulating this through the extension or manually should fix these issues.

**Comment by Pi-Mania** [comment]
Run in Docked-Mode Fixes Screen Flip issues.

**Comment by legend800** [comment]
Same for Fight N Rage and Streets of Rage 4.

**Comment by benderscruffy** [comment]
not fixed on my AMD RX 580 with #3885

**Comment by edave64** [comment]
This issue still seems to occur in Undertale
![image](https://user-images.githubusercontent.com/361185/85905564-03bc1e80-b80c-11ea-8482-91dc7e002127.png)

Only occurs on Vulkan.

GPU: Radeon RX Vega M GH

**Comment by 1900forever** [comment]
Same issue in Streets of Rages
![20201122205253](https://user-images.githubusercontent.com/3516677/99923672-cbf6cb80-2d04-11eb-85d3-aff66d2eb470.png)

**Comment by dudulins** [comment]
Have the same issue with "Fire Emblem Shadow Dragon and the Blade of Light". Emulation is very slow and the screen is upside down using Vulkan (both docked or in handheld). The game does not boot with OpenGL.

**Comment by bastol85** [comment]
Streets of rage 4 and celeste now run the right way but not katana zero.

**Comment by benkhouya** [comment]
Same issue with the game **LAYTON’S MYSTERY JOURNEY: Katrielle and the Millionaires’ Conspiracy – Deluxe Edition** using vulkan with yuzu early access build 1705

**Comment by JeonDohyeon** [comment]
> Same issue with the game **LAYTON’S MYSTERY JOURNEY: Katrielle and the Millionaires’ Conspiracy – Deluxe Edition** using vulkan with yuzu early access build 1705

![image](https://user-images.githubusercontent.com/34373595/124369626-a1acb980-dca8-11eb-8a4c-3f991c151fba.png)
Same here, at standard build 676. Console works fine right now.

**Comment by Silejonu** [comment]
> Streets of rage 4 and celeste now run the right way but not katana zero.

Celeste is still partially upside-down.
Some textures are still reversed, in addition to being broken.
Tested on both OpenGL and Vulkan, with a Radeon RX 570, using the Flatpak version, on Arch Linux.
![01002b30028f6000_2021-07-17_23-49-26-771](https://user-images.githubusercontent.com/48565914/126050078-f9f56a7b-ccc4-4d0c-adc6-af17f58d5f7e.png)

**Comment by v1993** [comment]
Please note that yuzu flatpak is an unofficial build and is not supported (it makes versioning very hard). Please use AppImages or build from git source, at least when reporting issues.

**Comment by Silejonu** [comment]
> Please note that yuzu flatpak is an unofficial build and is not supported (it makes versioning very hard). Please use AppImages or build from git source, at least when reporting issues.

Alright, I'll do that in the future. for the record, the same bug is present in the AppImage, version yuzu-20210718-f43ce79c7.

**Comment by benderscruffy** [comment]
using latest EA
Celeste and Axiom Verge are still upside down in Vulkan and Opengl on my Radeon RX 580

**Comment by StHiryu** [comment]
Streets of rage 4 seems not to be fixed at all... Using OpenGL and Nvdia Geforce 
GT730 with Drivers 391.35.

![sor4](https://user-images.githubusercontent.com/93271703/139784172-90fa8344-dbda-4f02-8f83-8c11bfd09ed2.jpg)

**Comment by bastol85** [comment]
It does work normally with vulkan and updated drivers

**Comment by StHiryu** [comment]
Also same problem with Bleed 2. Works fine on Ruyjinx emu.

![Bleed2Switch](https://user-images.githubusercontent.com/93271703/141216252-55065db1-05af-4f89-94dd-60371c55072c.jpg)

**Comment by djungelurban** [comment]
Did someone say this was fixed in Celeste? Cause it really ain't..
![01002b30028f6000_2021-12-11_01-42-57-587](https://user-images.githubusercontent.com/92630541/145657383-ea333115-763e-4d6b-8d3e-270e0ebbe35d.png)
.

**Comment by benderscruffy** [comment]
hammerwatch is also flipped
![01003b9007e86000_2021-12-11_11-39-48-644](https://user-images.githubusercontent.com/2696404/145662482-45fd9053-2398-4211-bf17-cc680fafa46d.png)

**Comment by bastol85** [comment]
> Did someone say this was fixed in Celeste? Cause it really ain't.. ![01002b30028f6000_2021-12-11_01-42-57-587](https://user-images.githubusercontent.com/92630541/145657383-ea333115-763e-4d6b-8d3e-270e0ebbe35d.png) . Atleast gameplay isn't flipped...
> 
> Oh, and only an updated version does this. Version 1.0.0.0 is the right side up.

![20211211_155207](https://user-images.githubusercontent.com/64667356/145681002-2c17e47b-a4b0-4603-a0b2-8ab49d8822da.jpg)

As you can see it works. 1.3 works. Use vulkan

**Comment by djungelurban** [comment]
But 1.4 doesn't, so while using a previous version solves the problem, there's still a problem...

**Comment by bastol85** [comment]
Bro just update your firmware and keys...

**Comment by StHiryu** [comment]
Use and support Riujinx. Works Perfectly with OpenGl...

**Comment by m1steron** [comment]
Hi all,

GPU specific issues? AMD Radeon RX series.
Using latest available build at time of writing v855.

Dead Cells - Vulkan corruption / works fine using Open GL

![0100646009fbe000_2021-12-08_11-34-22-004](https://user-images.githubusercontent.com/96198238/146952933-41f26e65-e0f5-4579-acfc-720b0826aaf8.png)
![0100646009fbe000_2021-12-08_11-36-00-205](https://user-images.githubusercontent.com/96198238/146952942-a4c82c7d-ecf4-4705-a635-a986b89d7e40.png)

Owlboy - Vulkan & OpenGL: screen orientation issue

![0100bc2004ff4000_2021-12-08_11-37-05-243](https://user-images.githubusercontent.com/96198238/146953380-0db11c93-be2c-4e1b-9445-d5ee0ddf2868.png)

Carrion - Vulkan & OpenGL: no image / can hear audio

![0100b1600e9ae000_2021-12-08_11-39-16-971](https://user-images.githubusercontent.com/96198238/146953436-126f6e9b-c383-4ee4-a6dd-378e7f548d98.png)
![0100b1600e9ae000_2021-12-08_11-39-29-923](https://user-images.githubusercontent.com/96198238/146953445-201427e4-287e-4f5a-a8fe-92593593b0ca.png)

Axiom Verge 2 -  Vulkan & OpenGL: screen orientation issue, graphic corruption, missing text.

![01002fc010240000_2021-12-08_11-48-05-843](https://user-images.githubusercontent.com/96198238/146953731-487b21b9-abc0-449d-bf7c-c4c79ae4c080.png)
![01002fc010240000_2021-12-08_11-48-43-419](https://user-images.githubusercontent.com/96198238/146953740-0bc165e8-c2aa-455a-b554-f469896e6ecc.png)
![01002fc010240000_2021-12-08_11-49-24-980](https://user-images.githubusercontent.com/96198238/146953746-888d0055-5cb7-4f7d-aa3a-629b77b688b7.png)

Celeste - Vulkan & OpenGL: screen orientation issue. Game plays correct orientation with upside down text.

![01002b30028f6000_2021-12-21_15-03-26-204](https://user-images.githubusercontent.com/96198238/146954580-e9bb767b-fca6-4778-97b0-4c40fa60224e.png)
![01002b30028f6000_2021-12-21_15-03-32-747](https://user-images.githubusercontent.com/96198238/146954614-aedab410-0dc7-443e-bfc2-7f4e614d8a6f.png)
![01002b30028f6000_2021-12-21_15-03-45-650](https://user-images.githubusercontent.com/96198238/146954622-90f96123-0068-4935-a554-70323ca181f8.png)
![01002b30028f6000_2021-12-21_15-04-31-851](https://user-images.githubusercontent.com/96198238/146954644-bae3492b-bc30-43c4-b1d5-2b0aeb7f94ea.png)

Full System Details:

CPU - Intel(R) Core(TM) i7-6700 CPU  - @ 3.40GHz 4 Cores
RAM - 16 GB
GPU - GPU - Radeon RX 580 Series - Primary/Discrete
VRAM - 8192 MB - GDDR5 2000 MHz
Graphics Card Manufacturer - Powered by AMD
Graphics Chipset - Radeon RX 580 Series
Device ID - 67DF
Vendor ID - 1002
SubSystem ID - 22FC
SubSystem Vendor ID - 1458
Revision ID - E7
Bus Type - PCI Express 3.0
Current Bus Settings - PCI Express 3.0 x16
BIOS Version - 015.050.002.001
BIOS Part Number - xxx-xxx-xxx
BIOS Date - 2018/04/09 07:07
Usable Memory Size - 8192 MB
Memory Type - GDDR5
Memory Clock - 2000 MHz
Core Clock - 1340 MHz
Total Memory Bandwidth - 256 GByte/s
Memory Bit Rate - 8.00 Gbps
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
OpenGL® API Version - 4.6
OpenCL™ API Version - 2.0
Software Version - 2021.1201.0115.2259
Driver Version - 21.40.11.03-211201a-374383E-RadeonSoftware
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01515
OpenGL® Version - 29.20.11000.14802
AMD Audio Driver Version - 10.0.1.23
Vulkan™ Driver Version - 2.0.204
Vulkan™ API Version - 1.2.196
Windows Version - Windows 10 (64 bit)

**Comment by saiyanvip** [comment]
> 

Hi,

I also have Street Of rage 4 backwards, it's the only game tested that has this problem.

I am using Batocera v32 (retrogaming special linux), yuzu.AppImage is installed with flatpak., I regularly update Yuzu hoping for a fix, but the problem is still present.

I have a GTX680 graphics card, the Nvdia driver is 470.63.01 paired with an I7 3770k.

Can the bug be corrected by another version or a "patch mod" or is it a problem of compatibility with the driver?

**Comment by dkoluris** [comment]
Here are logs from both Streets of Rage 4, and Guacamelee! 2, both appear upside down:

Specs: AMD Radeon 5500M (latest drivers) 4GB VRAM
[yuzu_log_streets_of_rage_4.txt](https://github.com/yuzu-emu/yuzu/files/8148685/yuzu_log_streets_of_rage_4.txt)
[yuzu_log_guacamelee_2.txt](https://github.com/yuzu-emu/yuzu/files/8148687/yuzu_log_guacamelee_2.txt)

**Comment by guoyunhe** [comment]
Same here, streets of rage 4. Please reopen this issue.

**Comment by ForgeableOne869** [comment]
> Games like Celeste and Axiom verge have the issue where the screen is rendered upside down, changes when APIs are swapped.
> 
> ![celeste1](https://user-images.githubusercontent.com/42394653/60931265-93289480-a27e-11e9-8b64-b8ebaa914e06.jpg)
> 
> ![celeste2](https://user-images.githubusercontent.com/42394653/60931264-93289480-a27e-11e9-9ed2-b44e4c7c671b.jpg)
> 
> ![celeste3](https://user-images.githubusercontent.com/42394653/60931263-93289480-a27e-11e9-8b23-ea556d22611d.jpg)
> 
> ![celeste4](https://user-images.githubusercontent.com/42394653/60931266-93289480-a27e-11e9-931e-f3113bc34c1b.jpg)

SOLVED IT for AMD RADEON. You got FSR toggle in the left down corner, change it. Fidelity Super Resolution was the cause for the flipped img.

**Comment by guoyunhe** [comment]
> SOLVED IT for AMD RADEON. You got FSR toggle in the left down corner, change it. Fidelity Super Resolution was the cause for the flipped img.

Not work for me

**Comment by chugalaefoo** [comment]
Streets of rage 4 on steamdeck still emulates updside down

**Comment by JumpLink** [comment]
Same for Stardew Valley, see #9368
