### ISSUE TITLE
Bayonetta 2 Broken Cutscene Rendering Bug

### ISSUE THREAD

**Issue by JOHN30011887** [yuzu-emu/yuzu#7411]
The fix #7349 #4220 that was done recently made a new bug in cutscenes, there is some sort of pixelation going on, 
but when you pause the game it fixes the issue cause pausing adds dof back in

It happens in Opengl and in Vulkan, no matter what settings or res scale used. and iv only seen it in the cutscenes.

Mainline 822
![yuzu_2021_11_22_12_18_59_508](https://user-images.githubusercontent.com/12979984/142861455-5fd7ae9f-dbab-4863-8598-f8ead3b87628.png)
![yuzu_2021_11_22_12_19_01_208](https://user-images.githubusercontent.com/12979984/142861472-4875c66a-1685-4c79-9688-43227d3ebde3.png)

These screenshots are from the Prologue level (World of Chaos) the very first cutscene of the level, you can also see issue on back of Enzo's head in this cutscene and issue happens in other levels too

**Comment by NineKain** [comment]
That might not be new, I think I saw that when I played last month, on the same level on the same hair

**Comment by JOHN30011887** [comment]
Hmm, well the version i had last before this 822 build was Mainline 810, i think its just a week old now if not less.
This is a screen from it (mainline 810) i just tested again just now at the same place, the cutscene blur bug is back in this version but the bug i reported here is gone.
![yuzu_2021_11_22_15_10_13_159](https://user-images.githubusercontent.com/12979984/142885901-d9c328e1-40ce-4def-8fee-36ae2f751f1c.png)

Hopefully this narrows the issue down for fixing in the future :)

**Comment by devrique** [comment]
Happening here on EA 2349 with characters' hair and clothes/hats:

![imagen](https://user-images.githubusercontent.com/1337227/147419840-5e19c7ff-7934-45f5-80ca-691e34fdcc94.png)

Also is fixed when pressing pause:

![imagen](https://user-images.githubusercontent.com/1337227/147419890-a348e22d-38e4-436f-b34a-ebcd24f549e7.png)
![imagen](https://user-images.githubusercontent.com/1337227/147419876-e1e3bf7e-635b-484f-9ea5-330564bde3a0.png)

-> Using AMD RX 480, Vulkan and Accuracy Level High.

**Comment by gidoly** [comment]
save file would be appreciate

**Comment by devrique** [comment]
@gidoly I think you can even see it on the first cinematic of a new game. Anyway, I can try to find the save file and upload it here.

Also, I'll try again just in case, as Yuzu was heavily updated and I didn't tried these last months.

**Comment by Lialeth** [comment]
Hi, just tried yuzu for the first time with bayonetta 2 and wanted to report the same issue. I experience the same bug on a custom fedora install, called nobara. The bug is present in the first cinematic of the game. Currently running this version:
![image](https://user-images.githubusercontent.com/105853956/182009128-82069024-9679-4387-89d5-a97ae647ec4c.png)
![image](https://user-images.githubusercontent.com/105853956/182009169-ab57da29-dd4b-4543-9dca-02311bb699db.png)

**Comment by augporto** [comment]
With EA2966 this issue is still present, but only with scaling higher than 1x , with 1x scaling the cut scenes render normally , higher than that it breaks.

**Comment by devrique** [comment]
@augporto I just finished the game this last weekend (using scaling x1) and for me there were some small issues with some face shadows in some specific scenes, but the game was really playable. No weird disappearing faces. :-)
