### ISSUE TITLE
Pokemon Legends Arceus 0 FPS issue (AMD CPU With Multicore Enabled)

### ISSUE THREAD

**Issue by ZantsuRocks** [yuzu-emu/yuzu#7804]
When playing Pokemons Legends Arceus after some time (not much) running the game smootly and stable the FPS goes down to 0 (sound keeps playing) and keep in this state forever.
This happens in Windows 11 and Ubuntu Linux too. This happens in both OpenGL and Vulkan.
My PC Specs: Ryzen 7 2700, AMD Radeon RX 5700, 20GB RAM

Screenshot of the issue
![image](https://user-images.githubusercontent.com/9502836/151666971-6e981666-f1e7-4dbf-99e4-bc43d31fb57a.png)

**Comment by FernandoS27** [comment]
@bunnei

**Comment by ZantsuRocks** [comment]
Maybe this can help
[yuzu_log.txt.txt](https://github.com/yuzu-emu/yuzu/files/7964042/yuzu_log.txt.txt)
.

**Comment by Koby411** [comment]
Same thing happens to me in both vulkan and opengl. Just drops to 0fps seemingly frozen in place but background music keeps playing.

PC Specs:
Ryzen 5 3600
RTX 3060
32GB DDR4-3600

**Comment by renatosk** [comment]
Same issue here , after 15 minutes or so of playing the game just stop but the music keeps playing
Ryzen 5 3600
RTX 3060

Maybe its only on AMD CPU?

**Comment by ZantsuRocks** [comment]
Ubuntu with OpenGL
![image](https://user-images.githubusercontent.com/9502836/151676728-19649548-eabe-44ae-a3ad-2dc45bafbb25.png)

Logfile have more than 76MB
heres a summary.
[logfile.txt](https://github.com/yuzu-emu/yuzu/files/7964691/logfile.txt)

**Comment by elgabo86** [comment]
Same here. 
I noticed that by disabling multicore cpu emulation, the problem does not occur.

AMD Ryzen 7 3700X
Nvidia RTX 2060 Super
Arch Linux

**Comment by ZantsuRocks** [comment]
> Same here. I noticed that by disabling multicore cpu emulation, the problem does not occur.
> 
> AMD Ryzen 7 3700X Nvidia RTX 2060 Super Arch Linux

This breaks the audio a lot, slows down the game a lot too but feels like solve the problem.

**Comment by FernandoS27** [comment]
Hmn it happens on some people but on others not. hmn

**Comment by Koby411** [comment]
> Same here. I noticed that by disabling multicore cpu emulation, the problem does not occur.
> 
> AMD Ryzen 7 3700X Nvidia RTX 2060 Super Arch Linux

Can confirm that disabling multicore seems to have solved the issue, but doing so makes the audio sound horrible and delayed.

**Comment by FernandoS27** [comment]
> > Same here. I noticed that by disabling multicore cpu emulation, the problem does not occur.
> > AMD Ryzen 7 3700X Nvidia RTX 2060 Super Arch Linux
> 
> Can confirm that disabling multicore seems to have solved the issue, but doing so makes the audio sound horrible and delayed.

I think I'll need a wait tree. To get a wait tree, pause the emulator after freeze, then go to View -> Debugging -> Wait Tree.

Pass me multiple screenshots of it.

**Comment by ZantsuRocks** [comment]
![image](https://user-images.githubusercontent.com/9502836/151680575-2fd0da2a-a832-4907-97d9-75a417541a3c.png)
![image](https://user-images.githubusercontent.com/9502836/151680582-b279b047-0072-4e12-b0be-95c55228f5aa.png)
![image](https://user-images.githubusercontent.com/9502836/151680592-d0dc40eb-8be4-4c46-b2a2-cbd087d3b72b.png)
![image](https://user-images.githubusercontent.com/9502836/151680597-16162287-ad7f-4501-b5f2-2facc7a69c5e.png)
![image](https://user-images.githubusercontent.com/9502836/151680606-e4d0f8e1-dc87-46e5-b495-732103b117da.png)

**Comment by ZantsuRocks** [comment]
Now the game stuck "forever"
![image](https://user-images.githubusercontent.com/9502836/151680680-de85dd4d-26b4-41d5-a817-7bb39f466970.png)
![image](https://user-images.githubusercontent.com/9502836/151680689-58fad0a2-fe3f-419e-9735-91f4e9edbb1d.png)
![image](https://user-images.githubusercontent.com/9502836/151680701-71d83d3a-43f5-4dc8-a0aa-8086da8c2397.png)
![image](https://user-images.githubusercontent.com/9502836/151680709-d12ecb3f-3b1e-4dc1-87b1-7b81dcf2e83c.png)
![image](https://user-images.githubusercontent.com/9502836/151680720-b046eab1-aab7-492c-903b-74dab2c92c46.png)

**Comment by henryfool91** [comment]
Same problem (0 fps, sound keeps playing) exist in Fitness Boxing 2 (sometimes occures in 1 minute, sometimes in 5 minutes), and yuzu stops responding on tries to pause or  reload game. Looks like disabling multicore cpu emulation fixes this, but the game becomes unplayable  cause of sound delay. 
![Аннотация 2022-01-30 031944](https://user-images.githubusercontent.com/82047953/151682265-70146fa7-d2a8-403a-a2c2-872f7abcd6da.jpg)
![Аннотация 2022-01-30 032019](https://user-images.githubusercontent.com/82047953/151682267-8df35190-d6d9-4380-8837-82e98a03a10f.jpg)

**Comment by gidoly** [comment]
set affinity to 4core seems walk around issue

**Comment by Koby411** [comment]
> set affinity to 4core seems walk around issue

Tried this. Still freezes up on my end too, but its not a permanent freeze oddly enough. 
At 4 core affinity if I wait just a few seconds it'll unfreeze and continue on.
If I try 6 core affinity, it will permanently freeze up.

**Comment by henryfool91** [comment]
Forget to mention my specs: Win 10, Ryzen 3600, Nvidia 2060, 32gb DDR4.
So, looks like this issue exist only on AMD CPU, hm?
Btw, where did you, guys, set affinity to 4core? Couldn`t find this setting

**Comment by Limetkaqt** [comment]
Tried the 4 affinity, there were 2 few second freezes, but game recovered itself, then after progressing further yuzu.exe just closed. Also everything seems fine with multicore support turned off, just FPS tanked. Using Ryzen 1400, Nvidia 760, 16GB DDR4, Win 11.

**Comment by FernandoS27** [comment]
@bunnei for when you are back from weekend vacation.

**Comment by FernandoS27** [comment]
Also, do you guys have the update on or not? If not, try turning it off.

**Comment by ZantsuRocks** [comment]
> Forget to mention my specs: Win 10, Ryzen 3600, Nvidia 2060, 32gb DDR4. So, looks like this issue exist only on AMD CPU, hm? Btw, where did you, guys, set affinity to 4core? Couldn`t find this setting

Tab "DETAILS" in windows task manager. Right click yuzu.exe and go to "set cpu affinity" (i don't know if this is the name in english windows) select CPU 0 through 3

**Comment by Limetkaqt** [comment]
> Also, do you guys have the update on or not? If not, try turning it off.

Tried without update as well, but same thing.

**Comment by ZantsuRocks** [comment]
> set affinity to 4core seems walk around issue

For me it's true.
Affinity 4 let the game unfreeze after some time when 0 fps happens.

**Comment by FernandoS27** [comment]
> > Also, do you guys have the update on or not? If not, try turning it off.
> 
> Tried without update as well, but same thing.

Thank you, sadly the dev that takes care of this stuffs is in a small weekend trip to AZ. He'll be back on monday.

**Comment by henryfool91** [comment]
> > Forget to mention my specs: Win 10, Ryzen 3600, Nvidia 2060, 32gb DDR4. So, looks like this issue exist only on AMD CPU, hm? Btw, where did you, guys, set affinity to 4core? Couldn`t find this setting
> 
> Tab "DETAILS" in windows task manager. Right click yuzu.exe and go to "set cpu affinity" (i don't know if this is the name in english windows) select CPU 0 through 3

Thanks, but for me changing affinity doesnt fix the problem - same fps drop to zero, and yuzu not responding. However, disabling multicore cpu emulation prevent this, but, as was mentioned, sound delay and overall performance becomes not playable (Fitness Boxing 2)

**Comment by Koby411** [comment]
> Also, do you guys have the update on or not? If not, try turning it off.

What update?

**Comment by shibotto** [comment]
> Also, do you guys have the update on or not? If not, try turning it off.

I don't want to get anyone's hope up too much, but since #7806 I've been playing for 3 hours straight without a single hang whereas previously it usually wouldn't last 15 minutes. If you don't hear from me again, it means it's not simply a lucky run.

Ryzen 2200G, no dedicated GPU, GNU/Linux.

**Comment by Koby411** [comment]
> > Also, do you guys have the update on or not? If not, try turning it off.
> 
> I don't want to get anyone's hope up too much, but since #7806 I've been playing for 3 hours straight without a single hang whereas previously it usually wouldn't last 15 minutes. If you don't hear from me again, it means it's not simply a lucky run.
> 
> Ryzen 2200G, no dedicated GPU, GNU/Linux.

Unless I'm misunderstanding something, I'm not sure how that would affect things here. From the sounds of things in that post, that fix seems to suggest it's mostly about Intel GPUs under Vulkan, but the issue here mostly seems to be related to AMD CPUs using multicore.

**Comment by shibotto** [comment]
It's either that or the current form of #7805, they are the only 2 things different from the last time I tried. But again, it might have been a very lucky run.

**Comment by karlis69420** [comment]
Issue fixed in #7827.

**Comment by shibotto** [comment]
It still freezes for me.

**Comment by ZantsuRocks** [comment]
> Issue fixed in #7827.

For me it's fully fixed.
Even the slow downs (that happened with the workaround) are fixed.

**Comment by henryfool91** [comment]
Still freezes in Fitness Boxing 2

**Comment by Koby411** [comment]
Freezes are much less frequent, but they're still happening for me in Pokemon Legends Arceus on mainline 906.

**Comment by FernandoS27** [comment]
> Freezes are much less frequent, but they're still happening for me in Pokemon Legends Arceus on mainline 906.

hmn, have you tried playing with coire affinity? only assign yuzu to the even or odd cores?

**Comment by Koby411** [comment]
Haven't had any more freezes in any of the updates.

**Comment by DiegoMadGlez** [comment]
I still have this problem, in some games it is more repetitive, it can be easily reproduced with Mario 3D all stars is literally unplayable, it happens in all the games I have.

**Comment by defaultex** [comment]
After getting log to console enabled, found this stack trace in my terminal when Arceus freezes. 

`[1517.394159] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:570: Signalling debugger, PANIC! info1=0x0000001052F46EB8, info2=0x0000000000000004
[1517.394164] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:operator():552: debug_buffer_err_code=0
[1517.394167] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:619: Emulated program broke execution! reason=0x0000000000000000, info1=0x0000001052F46EB8, info2=0x0000000000000004
[1517.394172] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:79: Backtrace, sp=0000001052F46DA0, pc=000000000D71DB58
[1517.394176] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:80: Module Name         Address             Original Address    Offset              Symbol
[1517.394179] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:82: 
[1517.458334] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 0000007100146888    000000000D4C4888    0000000000146888    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[1517.458340] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 0000007100145034    000000000D4C3034    0000000000145034    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_RSt9__va_list
[1517.458343] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 0000007100145194    000000000D4C3194    0000000000145194    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_i
[1517.458345] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 0000007100351234    000000000D6CF234    0000000000351234    _ZN2nn2os6detail38InternalConditionVariableImplByHorizon9TimedWaitEPNS1_23InternalCriticalSectionERKNS1_13TimeoutHelperE
[1517.458349] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 0000007100345F88    000000000D6C3F88    0000000000345F88    _ZN2nn2os14TimedWaitEventEPNS0_9EventTypeENS_8TimeSpanE
[1517.458353] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: main                0000007102DF5C88    000000000ADF9C88    0000000002DF5C88    
[1517.458357] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 0000007100349D94    000000000D6C7D94    0000000000349D94    
[1517.458360] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 00000071003501D0    000000000D6CE1D0    00000000003501D0    
[1517.458363] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:86: sdk                 00000070F2C81FFC    FFFFFFFFFFFFFFFC    FFFFFFFFF2C81FFC    
`

For reference system configuration is:
CPU: AMD Ryzen 3 3200G with Vega blacklisted in the boot args.
Graphics Card: AMD Radeon R7 260X using kisak-mesa drivers.
Memory: 16GB Corsair Vengence (2x 8GB sticks in dual channel sockets at 2133MHz).
Mainboard: ASUSTek TUF Gaming X570-PLUS
OS: Linux Mint 20.3 
Kernel: 5.10.111-xanmod1
Storage: 1TB WD Blue (where /home, /var, and /tmp lives) and HP EX900 250GB m.2 (where the system and games live)
Controller: Generation 1 Xbox360 Wired gamepad (served using xpad module)
Additional: Launched with gamemode enabled but does it without as well.

**Comment by Pajn** [comment]
Also getting this  crash. Game works but is of course slow and sound choppy with multicore disabled

```
[ 838.387931] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:246: (STUBBED) called
[ 838.389186] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:246: (STUBBED) called
[ 838.389263] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:246: (STUBBED) called
[ 838.389318] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:246: (STUBBED) called
[ 838.389414] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:246: (STUBBED) called
[ 838.485103] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:246: (STUBBED) called
[ 838.900787] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 838.905645] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 838.907612] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 838.912534] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 838.914530] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 838.915369] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 838.916584] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 838.917425] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 840.934829] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 840.940283] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 840.949394] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 840.950221] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.100117] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.101486] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.103098] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.108645] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.112322] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.113314] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.114716] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.115584] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.116808] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.117654] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.119349] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.120210] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.123112] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.126040] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.136469] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.140290] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.141418] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.142243] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.146060] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.146841] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.147801] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 843.148581] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 845.059489] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1508: (STUBBED) called, result=0x000002A2
[ 845.060180] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:571: Signalling debugger, PANIC! info1=0x0000001014879EB8, info2=0x0000000000000004
[ 845.060186] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():552: debug_buffer_err_code=0
[ 845.060191] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:622: Emulated program broke execution! reason=0x0000000000000000, info1=0x0000001014879EB8, info2=0x0000000000000004
[ 845.060194] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:79: Backtrace, sp=0000001014879DA0, pc=000000000D71DB58
[ 845.060199] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:81: Module Name         Address             Original Address    Offset              Symbol
[ 845.060200] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:82: 
[ 845.156849] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100146888    000000000D4C4888    0000000000146888    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[ 845.156854] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100145034    000000000D4C3034    0000000000145034    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_RSt9__va_list
[ 845.156855] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100145194    000000000D4C3194    0000000000145194    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_i
[ 845.156857] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100351234    000000000D6CF234    0000000000351234    _ZN2nn2os6detail38InternalConditionVariableImplByHorizon9TimedWaitEPNS1_23InternalCriticalSectionERKNS1_13TimeoutHelperE
[ 845.156858] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100345F88    000000000D6C3F88    0000000000345F88    _ZN2nn2os14TimedWaitEventEPNS0_9EventTypeENS_8TimeSpanE
[ 845.156859] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007102DF5C88    000000000ADF9C88    0000000002DF5C88    
[ 845.156860] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100349D94    000000000D6C7D94    0000000000349D94    
[ 845.156861] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 00000071003501D0    000000000D6CE1D0    00000000003501D0    
[ 845.156862] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 00000070F2C81FFC    FFFFFFFFFFFFFFFC    FFFFFFFFF2C81FFC    
```

**Comment by vivi3107** [comment]
@defaultex @Pajn
Same issue here. I tested many early access builds and I figured out that the regression happened in EA2674/2675 so possibly this change #8188 is problematic. Using EA2673 I can play for hours without freezes and crashes.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8846437/yuzu_log.txt)
.

**Comment by G-Spawn** [comment]
Closing this issue as almost every log provided contained pirated content. Feel free to dump all your files from your nintendo switch @vivi3107  @ZantsuRocks if you desire support here.
