### ISSUE TITLE
Kirby and the Forgotten Land Demo issue compilation

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#7979]
placeholder

**Comment by Morph1984** [comment]
Complete save file
[010091201605A000.zip](https://github.com/yuzu-emu/yuzu/files/8188588/010091201605A000.zip)

**Comment by Morph1984** [comment]
### Broken rendering on Intel RocketLake Xe, OpenGL, Windows
![image](https://user-images.githubusercontent.com/39850852/156837057-5ea150e6-9164-4667-8296-140c4353853e.png)
![image](https://user-images.githubusercontent.com/39850852/156837305-31b38a00-4d78-4be0-89ad-bce44e6b23af.png)

**Comment by lat9nq** [comment]
Using RadeonSI has some extra rendering issues.

<img alt="Screenshot from 2022-03-04 15-30-33" src="https://user-images.githubusercontent.com/22451773/156842387-56f95c02-0047-4c89-acd3-561b9ea7029f.png" width=600 />
<img alt="Screenshot from 2022-03-04 15-33-00" src="https://user-images.githubusercontent.com/22451773/156842399-bd02619e-46ac-4ac8-ab87-fedcafeaa754.png" width=600 />

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8188781/yuzu_log.txt)

**Comment by lat9nq** [comment]
ANV has a shadow issue. Originally I had a device loss at the beginning of the cutscene following the car crossing the bridge, but could not reproduce.

![Screenshot from 2022-03-04 16-21-30](https://user-images.githubusercontent.com/22451773/156844329-b59c2672-9623-41f6-a17e-5f1523790801.png)

**Comment by bajulador** [comment]
The game is performing well (30 FPS during gameplay and 60 FPS at other times). But I got two freezes at the same level. I couldn't get a look at the moment when the game freezed, but I'm pretty sure I hit 4GB VRAM. Here's a picture that I could get after right freezing:
![kirby](https://user-images.githubusercontent.com/59267216/160163558-7b496341-3bdb-4628-afc0-22dfe62814d5.jpg)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8352346/yuzu_log.txt)

**Comment by ZoruaLoL** [comment]
I would like to add that the crashes have become a lot more frequent after build 963 (the game freezes but the music plays at normal speed, and the emulator becomes irresponsive), sometimes even doing it before the title screen loads up.

**Comment by funtimeandrefoxy** [comment]
The "Softlocks Svcbreak" issue is not fixed.

**Comment by RinMaru** [comment]
> I would like to add that the crashes have become a lot more frequent after build 963 (the game freezes but the music plays at normal speed, and the emulator becomes irresponsive, RAM utilization remains normal however), sometimes even doing it before the title screen loads up.

yep had a crash this morning. seems to be Shader build related possibly

**Comment by SmitheeGuy** [comment]
Since nobody mentioned that i'll contribute with **screwed tangents/vertex normals** on **Elevator**, **Glider** and **Truck** Mouth modes.
Any settings, mods, whatever... it's just there like that.
Car, Gotcha Machine, Ring, Lightbulb, Cone, Roller-coaster, Water baloon are fine.

![Yuzu_KATFL_Elevator](https://user-images.githubusercontent.com/60198011/160768202-90a6dd3a-6ae8-455d-bfb5-cc487c63f4a9.png)
![Yuzu_KATFL_Glider](https://user-images.githubusercontent.com/60198011/160768207-1d6a539a-05ba-48fb-8001-6537ac58c0ca.png)
![Yuzu_KATFL_Truck](https://user-images.githubusercontent.com/60198011/160768209-d00ff81f-638f-493d-bbee-c116959181c8.png)

**Comment by lKomus** [comment]
Well, Async GPU can be turned on or off for me, it makes no difference. The sand in the desert is glitchy like in your first screenshot.

**Comment by ZoruaLoL** [comment]
> yep had a crash this morning. seems to be Shader build related possibly
Seems fixed by build 971

**Comment by ZantsuRocks** [comment]
This vertex explosion keeps happening to me in 2665 EA
https://user-images.githubusercontent.com/39850852/160153944-df635cfa-4699-415a-9d2c-85b1b96212ec.png

**Comment by RiedleroD** [comment]
In my case, the HUD starts to flicker and disappear a few seconds in while the framerate drops dramatically. Reducing resolution does nothing to this issue, so I assume it's something to do with the CPU emulation. Also, according to nvtop, neither VRAM nor GPU computing is even 50% used, though I can't fully rule out some bottleneck-y GPU instruction.

I've got a Nvidia GTX 750 Ti with proprietary drivers and am running this on X11/i3. All rendering APIs are affected, other games run fine.

**Comment by jscoys** [comment]
> This vertex explosion keeps happening to me in 2665 EA https://user-images.githubusercontent.com/39850852/160153944-df635cfa-4699-415a-9d2c-85b1b96212ec.png
> 
> Windows 11 AMD RX 5700 (Driver version 22.4.1) Vulkan API. FSR enabled.

Same here for Vertex explosion, with EA 2683, it happens only in Waddle Dee Town and randomly. If it happens, I go to the world star and then come back, it generally disappears. So it still happening, but it improved a lot compared to 1 month ago when it was happening at different places and really more often ;-)

**Comment by taifengdian** [comment]
The game can't keep running at 60Hz all the time. Sometimes the frame drops very badly. I try it last time with EA 2729. Does anyone else have such a problem？

**Comment by good-praxis** [comment]
I am running into a persistent freeze/crash with yuzu on a late stage game: Forgo Horns in the Isolated Isles. Occurs within the first camera pan in the first sublevel. Logs don't seem to contain anything useful but here you go:

```
[ 239.231044] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.231046] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.266764] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.266771] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.266773] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.302005] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.302013] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.302014] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.340773] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.340782] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.340783] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.371544] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.371552] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.371555] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.400456] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.400464] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.400466] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.437489] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.437499] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.437502] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.464116] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.464125] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.464127] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.503317] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.503335] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.503339] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.532868] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.532880] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.532885] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.577824] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.577832] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.577834] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.611668] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.611677] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.611679] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.649983] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.649991] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.649993] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.675003] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.675012] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.675014] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.709229] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.709237] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.709239] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.745367] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.745374] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.745376] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.793196] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.793203] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.793205] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.860514] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.860521] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.860523] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.904692] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.904711] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.904713] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.932374] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.932382] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.932384] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.968228] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.968236] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.968238] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 239.993513] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 239.993520] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 239.993523] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 240.037243] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 240.037250] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 240.037252] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 241.290440] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 241.299107] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 241.300141] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 241.466394] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 241.468561] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 241.470779] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 241.472525] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 241.816618] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():226: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}
[ 241.816626] Debug <Critical> ./video_core/texture_cache/samples_helper.h:operator():50: Assertion Failed!
Invalid MSAA mode=15
[ 241.816628] Debug <Critical> video_core/texture_cache/image_info.cpp:operator():97: Assertion Failed!
Invalid texture_type=15
[ 243.846635] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 243.847746] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 243.848628] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.353187] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.354083] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.355744] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.356691] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.361146] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.362102] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.367996] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.368876] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocParam:201: (STUBBED) called type=1
[ 246.413001] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Initialize:65: (STUBBED) called
[ 246.414076] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xB71B00, max=0xFFFFFFFF
[ 246.414849] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.452800] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.453074] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.456341] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.456707] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.456912] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.487175] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.487484] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp:SetSubmitTimeout:181: (STUBBED) called
[ 246.487577] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.488563] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.489251] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.489344] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.489879] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.490623] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.490991] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.491529] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.491874] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.491942] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.492237] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.492313] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.492586] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:SetAndWait:84: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 246.492669] Service.MM <Warning> core/hle/service/mm/mm_u.cpp:Get:93: (STUBBED) called
[ 246.492841] Service.MM <Warning> core/hl
```

Log just cuts off and a coredump is created. This crash only occurs on yuzu and running the level in ryujinx works just fine. I also tried disabling all optimizations and the like, trying to see if it's something specific but yuzu always crashes here. Can anyone reproduce?

**Comment by thisismypassport** [comment]
So did the vertex explosion fix ever got in? The PR that fixes it ( https://github.com/yuzu-emu/yuzu/pull/8127 ) seems to have been closed instead of merged?
The issue is still happening as of yuzu 1154.
A shame this (or anything else) wasn't mentioned in the official compatibility list.

**Comment by Testsr** [comment]
It would be good if Yuzu could fix the Vertex explosions with Vulkan, as the other backend, OpenGL, is very slow when running this game. Still happens Yuzu 1350.

**Comment by ultra-azu** [comment]
On yuzu 1478, I get a freeze similar to what @good-praxis describes, on Alivel Mall (Staff Side), Originull Wasteland. In between the start and a bit after getting RingMouth, the freeze happens.  However my log is pretty different other than yuzu cutting off. 

[yuzu_log_crash_kftl_3.txt](https://github.com/yuzu-emu/yuzu/files/11884306/yuzu_log_crash_kftl_3.txt)
