### ISSUE TITLE
Monster Hunter Rise v10.0.2 completely breaks the graphics.

### ISSUE THREAD

**Issue by Monaghan97** [yuzu-emu/yuzu#8519]
I have tested this on both regular and Early Access builds of Yuzu, to which I got the exact same results.

Yuzu version 1069
![yuzu](https://user-images.githubusercontent.com/80481111/176567845-baa9d7f5-7e81-440f-abc5-b4e726fabace.png)

Yuzu Early Access version 2805
![yuzu early access](https://user-images.githubusercontent.com/80481111/176567893-64169996-5352-4c20-87fc-a54da8e13955.png)

Please also note that I tested this on both OpenGL & Vulkan. Trying both Normal/High GPU accuracy.

Any earlier build of this game renders perfectly. It seems the newest SUNBREAK update (v10.0.2) is what is causing graphical issues.

PC Specs if needed
-------------------
GPU - NVIDIA RTX 2060 Super
CPU - AMD Ryzen 7 3700x
16GB RAM

**Comment by DarkermX** [comment]
Hope this gonna be fixed soon

**Comment by DarkermX** [comment]
**Any earlier build of this game renders perfectly.**
How ? it was neevr perfect. It has so many graphical glitches specially skybox and few more Area rendering bug

**Comment by Monaghan97** [comment]
> **Any earlier build of this game renders perfectly.**
> How ? it was neevr perfect. It has so many graphical glitches specially skybox and few more Area rendering bug

I'm just going off of my personal experiences with the game. I havent seen many graphical bugs on previous versions of MH Rise. Maybe by the time I played it, some glitches were fixed but in my experience it rendered perfectly.

**Comment by FernandoS27** [comment]
any log?

**Comment by Monaghan97** [comment]
> any log?

Apologies, I must have forgotten. I will add my log asap

**Comment by FernandoS27** [comment]
seems ASTC 10x6 is not implemented.

@Morph1984 easy hanging fruit.

**Comment by holmes5800** [comment]
game version 13.0.0
on yuzu EA 3311 
graphic still broken

and why when booting this game 
console mode would be changed from docked to handled

**Comment by aokman** [comment]
Monster Hunter Rise works fine with latest yuzu EA without Sunbreak Update installed.
But after apply Sunbreak Update, models begin to flicker (blink).

**Comment by willianholtz** [comment]
When there are text dialogs, these artifacts occur on the screen!

![error](https://github.com/yuzu-emu/yuzu/assets/23488207/234581fe-a834-4591-891a-9d0bc88ac7e4)

**Comment by GiancarloP1** [comment]
version 1.16.1 of monster hunter rise still has errors in graphics in the models
