### ISSUE TITLE
The Legend of Zelda - Breath of the Wild"Core.ARM <Error>"

### ISSUE THREAD

**Issue by afonu** [yuzu-emu/yuzu#8609]
Hi developers, I'm having an issue with "Core.ARM Error" while playing The Legend of Zelda - Breath of the Wild

My hardware devices are as follows:

CPU: Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz 2.21 GHz
RAM: DDR4 16GB
GPU: NVIDIA GeForce RTX3060 Laptop
SYSTEM: WINDOWS 11 64Bit

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9143611/yuzu_log.txt)

**Comment by G-Spawn** [comment]
We dont support piracy here @TheYang

**Comment by afonu** [comment]
Oh no, I'm a subscription member!~

**Comment by G-Spawn** [comment]
@afonu I wasnt replying to you sorry I had to delete a random comment and log from someone else.

**Comment by afonu** [comment]
Oh, I'm sorry! ~It's a misunderstanding

**Comment by afonu** [comment]
I tried to turn off the multi-core CPU simulation, and it was stable after playing for 1 hour, and then it crashed after turning it on!~

**Comment by afonu** [comment]
Can someone please solve this problem? Otherwise, there is no way to play!

**Comment by G-Spawn** [comment]
These issues aren't always fixed in a day. Please give it time.

**Comment by G-Spawn** [comment]
The issue has been reported by many and the devs are looking into it. Pardon the inconvenience 🙏 

Technically there is a way to play, but it would be you using older yuzu version prior to where issue occurs.

**Comment by TheYang** [comment]
[1069](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1069) has been working for me

**Comment by afonu** [comment]
> 許多人報告了這個問題，開發人員正在調查它。不便之處請見諒🙏
> 
> 從技術上講，有一種方法可以玩，但是在出現問題之前，您將使用舊的 yuzu 版本。

ok i'll try it, thank you!

**Comment by TheYang** [comment]
still happening:

`[ 290.980936] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:246: (STUBBED) called
[ 371.577374] Service.AM <Warning> core/hle/service/am/am.cpp:SetTerminateResult:1531: (STUBBED) called, result=0x0000EA01
[ 371.577601] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:568: Signalling debugger, PANIC! info1=0x000000100C303BB8, info2=0x0000000000000004
[ 371.577686] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:operator():550: debug_buffer_err_code=EA01
[ 371.577691] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:617: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100C303BB8, info2=0x0000000000000004
[ 371.577693] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:96: Backtrace, sp=000000100C3039F0, pc=000000000B805BA8
[ 371.577710] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:97: Module Name         Address             Original Address    Offset              Symbol
[ 371.577711] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:99: 
[ 371.652141] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710037EBA8    000000000B805BA8    000000000037EBA8    
[ 371.652147] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 00000071001801E8    000000000B6071E8    00000000001801E8    nn::diag::detail::Abort(nn::Result const*)
[ 371.652148] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710017ED3C    000000000B605D3C    000000000017ED3C    
[ 371.652164] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710017EE08    000000000B605E08    000000000017EE08    
[ 371.652165] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710032F83C    000000000B7B683C    000000000032F83C    
[ 371.652165] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 0000007100326AD4    000000000B7ADAD4    0000000000326AD4    nn::os::LockMutex(nn::os::MutexType*)
[ 371.652166] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                000000710124F1CC    00000000092531CC    000000000124F1CC    
[ 371.652167] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                0000007101614CA0    0000000009618CA0    0000000001614CA0    
[ 371.652168] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                0000007101614950    0000000009618950    0000000001614950    
[ 371.652169] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                0000007101250B2C    0000000009254B2C    0000000001250B2C    
[ 371.652170] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                0000007100E562F4    0000000008E5A2F4    0000000000E562F4    nnMain
[ 371.652171] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 0000007100296C9C    000000000B71DC9C    0000000000296C9C    nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
[ 371.652171] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: rtld                00000071000000C0    00000000080000C0    00000000000000C0    `

any other place one could track progress on this issue?

**Comment by AraqWeyr** [comment]
I've been checking on the similar issue on Linux and accidentally found this one.
Could this https://github.com/yuzu-emu/yuzu/issues/8778 be the same issue? Perhaps this issue is entirely platform and API agnostic. I could reproduce it both on Vulkan and OpenGL on an AMD GPU.

**Comment by liamwhite** [comment]
Fixed by #9474
